# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

config:
  partial_parse: false
  use_colors: true
  printer_width: 80
  send_anonymous_usage_stats: false

mj_dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}" 

      # User/password auth, get from environmental variables (github actions encrypted secrets)
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}" 
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}" 

      role: SYSADMIN
      database: MJ_DWH_DEV
      warehouse: COMPUTE_WH
      schema: dbt
      threads: 1
      client_session_keep_alive: False
      query_tag: default_dbt_tag

    tst:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}" 

      # User/password auth, get from environmental variables (github actions encrypted secrets)
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}" 
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}" 

      role: SYSADMIN
      database: MJ_DWH_TST
      warehouse: COMPUTE_WH
      schema: dbt
      threads: 1
      client_session_keep_alive: False
      query_tag: default_dbt_tag

    acc:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}" 

      # User/password auth, get from environmental variables (github actions encrypted secrets)
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}" 
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}" 

      role: SYSADMIN
      database: MJ_DWH_ACC
      warehouse: COMPUTE_WH
      schema: dbt
      threads: 1
      client_session_keep_alive: False
      query_tag: default_dbt_tag
    
    prd:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}" 

      # User/password auth, get from environmental variables (github actions encrypted secrets)
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}" 
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}" 

      role: SYSADMIN
      database: MJ_DWH_PRD
      warehouse: COMPUTE_WH
      schema: dbt
      threads: 1
      client_session_keep_alive: False
      query_tag: default_dbt_tag

    example:
      type: snowflake
      account: [account id]

      # User/password auth
      user: [username]
      password: [password]

      role: [user role]
      database: [database name]
      warehouse: [warehouse name]
      schema: [dbt schema]
      threads: [1 or more]
      client_session_keep_alive: False
      query_tag: [anything]
 
