name: Run a deploy action with DBT to the Snowflake environment

# run pipeline when there is a push to main branch
on:
  push:
    branches:
      - main

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        stale-issue-message: 'This issue has become stale and will be closed automatically within a period of time. Sorry about that.'
        stale-pr-message: 'This pull request has become stale and will be closed automatically within a period of time. Sorry about that.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 90 
