name: Run a deploy action with DBT to the Snowflake environment

# run pipeline when there is a push to main branch
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  install-and-run-dbt:

    runs-on: ubuntu-latest
    
    container: 
      image: python:3.7
      options: -u root

    steps:
    #- uses: actions/stale@v3
    #  with:
    #    stale-issue-message: 'This issue has become stale and will be closed automatically within a period of time. Sorry about that.'
    #    stale-pr-message: 'This pull request has become stale and will be closed automatically within a period of time. Sorry about that.'
    #    stale-issue-label: 'no-issue-activity'
    #    stale-pr-label: 'no-pr-activity'
    #    days-before-stale: 90 
        
    - task: DownloadSecureFile@1
      name: SettingProfile
      displayName: 'Downloading Profile for Snowflake'
      inputs:
        secureFile: 'mj-snowflake-dbt-profile.yml'

    - script: |
        echo Installing $(SettingProfile.secureFilePath) to the ~/.dbt...
        mkdir ~/.dbt
        cp $(SettingProfile.secureFilePath) ~/.dbt/profiles.yml
      displayName: Installing Profile for Snowflake
    
    - script: |
        pip install dbt --user
        export PATH=$PATH:/home/vsts_azpcontainer/.local/bin
        cd snowflake_tpc_demo
        dbt compile
        dbt test
        dbt run
      displayName: 'Compile, Test, and Run'    
